### ISSUE TITLE
Consider compatibility with Streams/Observables as per ES8 proposal

### ISSUE THREAD

**Issue by far-blue** [knockout/tko.observable#2]
There's a standards proposal for ES8 (https://github.com/tc39/proposal-observable) which takes the bare bones of the observer/subscriber pattern from most.js, rxjs, xstream, zen-observable etc. to provide some compatibility in the same way Promises became standardised.

I don't think KO's observer/subscriber pattern is very far away from the suggested standard and it would be cool if KO observables could interop.

As an example of how these libraries work, I found this tutorial helpful :) https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

As you can see, where the tutorial talks about streams of DOM events or subscribers updating the DOM, KO could slot in very neatly :)

**Comment by brianmhunt** [comment]
Thanks !  This is was just reported on the tko repo too - can't get to link but will try later. 

Great link 👍
